---
latitude: 40.70164
longitude: -73.99553
map_zoom: 12
name: 1 Hotel Brooklyn Bridge
email: steffan@traveltripper.io
phone_number: 001-111-1111
address:
  street1: 60 Furman Street
  street2: ''
  state: New York
  city: Brooklyn
  country: United States
  zip_code: '11201'
_hotel_id: 1HO373
_portal_id: required-but-empty
_ttweb_plugins_version: v2
_root_path: http://rtexpress-qa.ttaws.com/rt
